# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"

  config.vm.network :private_network, :auto_config => true , :ip => "192.168.56.5"
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize [ "modifyvm", :id, "--nicpromisc2", "allow-all" ]
  end

  config.omnibus.chef_version = :latest
  config.librarian_chef.cheffile_dir = "chef"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = ["chef/cookbooks"]
 
    chef.run_list = [
      "recipe[mysql::server]",
      "recipe[co-nfs::server]",
      "recipe[co-nfs::exports]",
      "recipe[nat-router]"
    ]

    chef.json = {
        "mysql" => {
          "server_root_password" => "",
          "server_repl_password" => "",
          "server_debian_password" => "",
          "allow_remote_root" => true,
        },
        "nfs" => {
          "exports" => [
            "/exports *(rw,async,no_root_squash)"
          ]
        }
    }
  end
end
