# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  ##
  # Brings up a management server, listening on 192.168.56.5
  # It provides Mysql, NFS and a gateway.
  #
  config.vm.define "management" do |management|
    management.vm.box = "chef/centos-6.5"

    # Set host only network
    management.vm.network :private_network, :auto_config => true , :ip => "192.168.56.5"
    management.vm.network "forwarded_port", guest: 3306, host: 3306

    # Set ram on VM.
    management.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
    end

    # Install Chef
    management.omnibus.chef_version = :latest
  
    # Download the required cookbooks
    management.librarian_chef.cheffile_dir = "management"

    management.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = ["management/cookbooks"]

      chef.json = {
          "mysql" => {
            "server_root_password" => "",
            "server_repl_password" => "",
            "server_debian_password" => "",
            "allow_remote_root" => true,
          },
          "nfs" => {
            "exports" => [
              "/exports *(rw,async,no_root_squash)"
            ]
          }
      }      
    end
  end

  ##
  # Brings up a XenServer hypervisor.
  #
  config.vm.define "xenserver" do |xenserver|
    xenserver.vm.box = "xenserver"

    xenserver.vm.provision "shell" do |s|
      s.path = "xenserver/reset-network.sh"
      s.args = ["eth1", "192.168.56.10", "255.255.255.0"]
    end
  end

end
