# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

unless Vagrant.has_plugin?('vagrant-librarian-chef')
  raise 'vagrant-librarian-chef is not installed!'
end

unless Vagrant.has_plugin?('vagrant-omnibus')
  raise 'vagrant-omnibus is not installed!'
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define 'xenserver' do |xenserver|
    xenserver.vm.box = 'duffy/xenserver'

    ## Map host only networks and the adapters
    xenserver.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      v.customize ["modifyvm", :id, '--nictype2', 'Am79C973']
    end

    # Configure Interface
    ## Configure Management Interface
    xenserver.vm.provision 'shell' do |s|
      s.path = '../common/xenserver/configure-network.sh'
      s.args = %w(eth1 192.168.22.10 255.255.255.0 MGMT)
    end

  end

  config.vm.define 'management' do |management|
    management.vm.box = 'chef/centos-6.5'

    management.vm.network :private_network, :auto_config => true, :ip => '192.168.22.5'

    management.vm.network 'forwarded_port', guest: 3306, host: 3306

    management.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--memory', 512]
      v.customize ["modifyvm", :id, '--nictype2', 'Am79C973']
    end

    management.omnibus.chef_version = "11.16.0"

    management.librarian_chef.cheffile_dir = '../common/management'

    management.vm.provision 'chef_solo' do |chef|
      chef.cookbooks_path = ['../common/management/cookbooks']

      chef.run_list = [
          'recipe[cloudstack::default]'
      ]
    end
  end
end
