# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

unless Vagrant.has_plugin?('vagrant-berkshelf')
  raise 'vagrant-berkshelf is not installed!'
end

unless Vagrant.has_plugin?('vagrant-omnibus')
  raise 'vagrant-omnibus is not installed!'
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define 'xenserver' do |xenserver|
    xenserver.vm.box = 'duffy/xenserver'

    ## Map host only networks and the adapters
    xenserver.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--hostonlyadapter2', 'vboxnet0']
      v.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
      v.customize ["modifyvm", :id, '--nictype2', 'Am79C973']
    end

    # Configure Interface
    ## Configure Management Interface
    xenserver.vm.provision 'shell' do |s|
      s.path = '../common/xenserver/configure-network.sh'
      s.args = %w(eth1 192.168.56.10 255.255.255.0 MGMT)
    end

  end

  config.vm.define 'management' do |management|
    management.vm.box = 'chef/centos-6.5'

    management.vm.network :private_network, :auto_config => true, :ip => '192.168.56.5'

    management.vm.network 'forwarded_port', guest: 3306, host: 3306

    management.vm.provider 'virtualbox' do |v|
      v.customize ['modifyvm', :id, '--memory', 512]
      v.customize ['modifyvm', :id, '--hostonlyadapter2', 'vboxnet0']
      v.customize ["modifyvm", :id, '--nictype2', 'Am79C973']
    end

    management.omnibus.chef_version = "11.16.4" 
    management.berkshelf.berksfile_path = File.join(File.dirname(__FILE__), 'Berksfile')
    management.berkshelf.enabled = true

    management.vm.provision 'chef_solo' do |chef|
      chef.run_list = [
          'recipe[cloudstack::default]'
      ]

      chef.json = {
        "cloudstack" => {
          "systemvms" => [
            {
              "hypervisor" => "XenServer",
              "url" =>  "http://jenkins.buildacloud.org/view/4.4/job/cloudstack-4.4-systemvm64/130/artifact/tools/appliance/dist/systemvm64template-4.4-2014-09-28-xen.vhd.bz2"
            }
          ]
        }
      }
    end
  end
end
