source "https://api.berkshelf.com"

cookbook 'hostname'
cookbook 'selinux'
cookbook 'nat-router', git: 'http://github.com/imduffy15/cookbook_nat-router'
cookbook 'cloudstack', git: 'https://github.com/imduffy15/cookbook_cloudstack-1'
cookbook 'cloudstack_vagrant_environment', path: '.provision-utils/cloudstack_vagrant_environment'